### ISSUE TITLE
Bir kişi her bir kategoride en fazla 3 robottan sorumlu olabilir. (Bir kişinin 7 kategoriye de katıldığını varsayarsak kategori başına 3 robottan hesaplandığında toplamda 21 robot ile katılabilir. Aynı kişinin bir kategoriye ait 3’den fazla robotu var ise, diğer robotlarını başka biri adına kayıt ettirmek zorundadır.)

### ISSUE THREAD

**Issue by akbasoguzhan** [okanmekatronik/robokan_19_kurallar#2]
Genel kurallar içindeki bu kuralın arazi robotu kategorisi için adaletsiz bir kural olduğunu düşünüyorum. 2 senedir bu yarışlara aktif olarak katılmaktayım ROBOKAN18 de dahil olmak üzere. Son katıldığım birkaç yarışta rakiplerimiz 13 robotla gelip bizim robotumuzdan her bakımdan daha işlevsiz robotuyla 13 kere deneme şansı sayesinde derece almayı başardılar. Maddi açıdan durumu yetenler var yetmeyenler var. Siz kişi başı 3 robottan bahsetmişsiniz. Ancak yarışmalara okul olarak katılındığı düşünülürse en az 10 kişi geliyorlar eğer ki imkanları varsa 30 robotla katılabilirler. Keşke her robotları birbirinden farklı olsa da 30 farklı fikir geliştirseler sınır koymayın derdim ama tek tipten robotla geldikleri için ben takıma sınır koyulması taraftarıyım. Örn: "Yarışmamıza 1 takım en fazla bir kategoride 3 robot kaydettirebilir." 
İyi günler dilerim
Saygılarımla,
Oğuzhan AKBAŞ

**Comment by mehmeteminkartal** [comment]
Merhaba arkadaşlarım size daha detaylı cevap verecektir. Lütfen burada kişisel bilgilerinizi paylaşmayın. Burası herkese açık bir forumdur. Teşekkürler
