### ISSUE TITLE
Organizasyona katılan her okul ya da grup için robotlarıyla ilgilenmeleri ve eşyalarını yerleştirmeleri amacıyla bir adet masa ayrılacaktır.

### ISSUE THREAD

**Issue by akbasoguzhan** [okanmekatronik/robokan_19_kurallar#3]
Genel kurallardaki bu kural aynı okuldan farklı takımlarda olabileceği için uygulanması uygun bir kural olmadığını düşünüyorum. En basitinden benim okulumdan en az 3 farklı takım çıkıyor. Ve şuanda benim okulumdan kayıt yaptıranlar var. Bu durumda ben ancak bireysel katılım yapabiliyorum. Bu sebepten dolayı kuralın düzenlenmesi gerektiğini düşünüyorum.

**Comment by mehmeteminkartal** [comment]
Merhaba Kurallarda gerekli düzeltmeyi yaptık. Her bir takım için ayrı masa verilecektir.
